openapi: 3.0.1
info:
  title: Swagger Users
  description: Description of Users endpoints declaration
  termsOfService: http://swagger.io/terms/
  contact:
    email: sixtus.nosike@metaenlace.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://colorbaby-users #Indicar url ra√≠z de la API
tags:
  - name: users
    description: All about users management
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:
  /auth/login:
    $ref: "./openapi/paths/login.yaml"
  /auth/logout:
    $ref: "./openapi/paths/logout.yaml"